apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skyops-weather-auth
  namespace: skyops-apps-dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: skyops-weather-auth
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: skyops-dev/apikey