apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skyops-db-auth
  namespace: skyops-apps-dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: skyops-db-auth
    creationPolicy: Owner
  data:
    - secretKey: auth-password
      remoteRef:
        key: skyops-dev/auth-password
    - secretKey: root-password
      remoteRef:
        key: skyops-dev/root-password
    - secretKey: secret-key
      remoteRef:
        key: skyops-dev/secret-key