apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: auth=187899929694.dkr.ecr.eu-north-1.amazonaws.com/skyops-auth
    argocd-image-updater.argoproj.io/auth.update-strategy: name
    argocd-image-updater.argoproj.io/auth.allow-tags: regexp:.* 
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh-key
    argocd-image-updater.argoproj.io/git-branch: main
spec: 
  project: default
  source:
    repoURL: https://github.com/sherif-abdelsalam/SkyOps.git
    targetRevision: main
    path: deployment/k8s/environments/dev/auth
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true