apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:sherif-abdelsalam/SkyOps.git
    targetRevision: main
    path: k8s/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true