apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:sherif-abdelsalam/SkyOps.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD/vKMbB8v8Gvmz3UGvFa9eSwGPKqR5W55jd8eqLYEy3wAAAKAjX98bI1/f
    GwAAAAtzc2gtZWQyNTUxOQAAACD/vKMbB8v8Gvmz3UGvFa9eSwGPKqR5W55jd8eqLYEy3w
    AAAEDv5d6PVqo87RGt2LJGNFj7vz/WXpNakJ9GXmsdCENnPP+8oxsHy/wa+bPdQa8Vr15L
    AY8qpHlbnmN3x6otgTLfAAAAF2tleSBmb3IgZ2l0bGFiID4gc2hlcmlmAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
